// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/kie.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const KIE_MODELS: ChatModelCatalog<typeof values, "kie"> =
	flattenChatModelCatalog("kie", values);

export const KIE_IMAGE_MODELS: ImageModelCatalog<typeof values, "kie"> =
	flattenImageModelCatalog("kie", values);

export const KIE_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "kie"> =
	flattenClassifierModelCatalog("kie", values);
